const travelDestinations: string[] = ["Tokyo”, “Paris”, “New York”, “Bali”, “Rome"];
console.log("Original Order:");
console.log(travelDestinations);
console.log("Alphabetical Order (without modifying the actual list):");
console.log([...travelDestinations].sort());
console.log("Array is still in its Original Order:");
console.log(travelDestinations);
console.log("Reverse Alphabetical Order (without modifying the actual list):");
console.log(...travelDestinations.sort().reverse());
console.log("Array is still in its Original Order:");
console.log(travelDestinations);
console.log("Reversed Order:");
travelDestinations.reverse();
console.log(travelDestinations);
console.log("Reversed Order (back to Original Order):");
travelDestinations.reverse();
console.log(travelDestinations);
console.log("Sorted in Alphabetical Order:");
travelDestinations.sort();
console.log(travelDestinations);
console.log("Sorted in Reverse Alphabetical Order:");
travelDestinations.sort().reverse();
console.log(travelDestinations);