let car: string = "subaru";
let age: number = 10;
let fruits: string[] = ["apple’, ‘banana’, ‘orange"];
console.log("Is car == subaru"? "i predict True.");
console.log(car == "subaru");
console.log("Is car != ‘honda’? I predict True.");
console.log(car != "honda");
console.log("Is car === ‘Subaru’? I predict False.");
console.log(car === "Subaru");
console.log("Is car !== ‘honda’? I predict True.");
console.log(car !== "honda");
console.log("Is age > 5? I predict True.");
console.log(age > 5);
console.log("Is age < 3? I predict False.");
console.log(age < 3);
console.log("Is age >= 10? I predict True.");
console.log(age >= 10);
console.log("Is age <= 8? I predict False.");
console.log(age <= 8);
console.log("Is car == ‘subaru’ && age > 5? I predict True.");
console.log(car == "subaru" && age > 5);
console.log("Is car == ‘honda’ || age > 10? I predict False.");
console.log(car == ‘honda’ || age > 10);
console.log("Is ‘banana’ in fruits? I predict True.");
console.log("banana" in fruits);
console.log("Is ‘grape’ not in fruits? I predict True.");
console.log("grape’ not in fruits");
